
# =============================================================================
# FILE 06: VISUALIZATIONS & PLOTS
# Generates publication-ready figures for the final report
# =============================================================================

library(ggplot2)
library(dplyr)
library(tidyr)

# Create directory for figures
dir.create("output/figures", showWarnings = FALSE)

# ── 1. FINITE SAMPLE CONVERGENCE (Simulation) ──────────────────────────────
cat("Generating Plot 1: Finite Sample Convergence...\n")

# Read the data generated by script 07
df_n <- read.csv("output/tables/3_sample_size.csv")

p1 <- ggplot(df_n, aes(x = N, y = Theta1_MSE, color = method, group = method)) +
  geom_line(linewidth = 1.2) +
  geom_point(size = 4) +
  scale_color_manual(values = c("probit" = "#2c3e50", "lasso" = "#e74c3c")) +
  theme_minimal(base_size = 14) +
  labs(
    title = "Finite Sample Convergence: Direct Effect",
    x = "Sample Size (N)",
    y = "Mean Squared Error (MSE)",
    color = "Estimator"
  ) +
  theme(legend.position = "bottom")

ggsave("output/figures/plot1_finite_sample.png", p1, width = 8, height = 5, dpi = 300)

# ── 2. GAMMA SENSITIVITY / IDENTIFICATION (Simulation) ─────────────────────
cat("Generating Plot 2: Gamma Sensitivity...\n")

df_gamma <- read.csv("output/tables/2_gamma_sensitivity.csv")

p2 <- ggplot(df_gamma, aes(x = gamma, y = DeltaT1_Bias, color = method, group = method)) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "gray50") +
  geom_line(linewidth = 1.2) +
  geom_point(size = 4) +
  scale_color_manual(values = c("probit" = "#2c3e50", "lasso" = "#e74c3c")) +
  theme_minimal(base_size = 14) +
  labs(
    title = "Sensitivity to Post-Treatment Confounding (\u03B3)",
    subtitle = "Bias in Total Indirect Effect",
    x = "Gamma (Strength of post-treatment confounding)",
    y = "Absolute Bias",
    color = "Estimator"
  ) +
  theme(legend.position = "bottom")

ggsave("output/figures/plot2_gamma_sensitivity.png", p2, width = 8, height = 5, dpi = 300)

# ── 3. EMPIRICAL APPLICATION COMPARISON (Job Corps) ────────────────────────
cat("Generating Plot 3: Empirical Comparison...\n")

# Read empirical data generated by script 05
emp_f <- read.csv("output/ml_comparison_females.csv")
emp_m <- read.csv("output/ml_comparison_males.csv")

# Combine and reshape data for plotting
emp_f$Gender <- "Female"
emp_m$Gender <- "Male"
emp_all <- rbind(emp_f, emp_m)

# We focus on theta_1 (Direct) and delta_t1 (Total Indirect)
emp_long <- emp_all %>%
  select(method, Gender, theta_1, delta_t1) %>%
  pivot_longer(cols = c(theta_1, delta_t1), names_to = "Effect", values_to = "Estimate") %>%
  mutate(Effect = ifelse(Effect == "theta_1", "Direct Effect (\u03B8\u2081)", "Total Indirect (\u03B4\u209C\u2081)"))

p3 <- ggplot(emp_long, aes(x = Effect, y = Estimate, fill = method)) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "gray50") +
  geom_bar(stat = "identity", position = position_dodge(width = 0.7), width = 0.6) +
  facet_wrap(~Gender) +
  scale_fill_manual(values = c("probit" = "#3498db", "lasso" = "#e67e22")) +
  theme_minimal(base_size = 14) +
  labs(
    title = "Job Corps Health Impacts: Probit vs. LASSO",
    x = "",
    y = "Estimated Effect on Health (Percentage Points)",
    fill = "Model"
  ) +
  theme(
    legend.position = "bottom",
    panel.grid.major.x = element_blank()
  )

ggsave("output/figures/plot3_empirical_effects.png", p3, width = 9, height = 6, dpi = 300)

cat("\n✓ All publication-ready plots saved to output/figures/ folder.\n")